### ISSUE TITLE
Documento Doc sobre metodologia da Atividade

### ISSUE THREAD

**Issue by LissaBatalha** [CulturaDigitaleEducacao/MemoriaDasRuas#11]
Doc para descrição da Atividade:
Posteriormente transcrever para o doc quando os pontos forem definidos:
https://docs.google.com/document/d/1kunP3zwkl77WO-oTFcjy16fical1udSnniqZ8HF_-Bk/edit?usp=sharing

**Comment by uira** [comment]
Duplicada com a #6
